name: 1ero

on:
  push:
    branches:
      - main

jobs:
  trabajando:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v6

      - name: instalando node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          
      - name: listar con el comando ls
        run: ls -la
      - name: pwd
        run: pwd
      - name: Instalar dependencias
        run: npm i
        
      - name: Build Angular
        run: npm run build
