name: 1ero

on:
  push:
    branches:
      - main

jobs:
  trabajando:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm i
      - name: listar
        run: ls -la
      - name: pwd
        run: pwd

      - name: Build Angular
        run: npm run build
